#!/usr/bin/env python
DEBUG = False
CC = "clang++"

libmotor_graphics = "window.cpp shader.cpp image.cpp camera.cpp"
libmotor_graphics = map(lambda x: "motor/graphics/" + x, Split(libmotor_graphics))

libmotor_io = "input.cpp socket.cpp"
libmotor_io = map(lambda x: "motor/io/" + x, Split(libmotor_io))

libmotor_utility = "time.cpp helper.cpp plot.cpp"
libmotor_utility = map(lambda x: "motor/utility/" + x, Split(libmotor_utility))

libmotor_math = "perlinNoise.cpp aabb.cpp"
libmotor_math = map(lambda x: "motor/math/" + x, Split(libmotor_math))

libmotor = libmotor_graphics + libmotor_io + libmotor_utility + libmotor_math

src_states = Split("state.cpp title.cpp game.cpp")

libs = Split("GL GLU GLEW SDL SDL_image")

cppPath = ["."]

if DEBUG:
	ccFlags = "-g -Wall -O0 -DDEBUG"# -std=c++0x"
else:
	ccFlags = "-g -Wall -O3"# -std=c++0x"


#Library("motor", libmotor, LIBS = libs, CPPPATH = cppPath)
#Program("awesome", "main.cpp", LIBS = libs + ["motor"], LIBPATH = ".", CPPPATH = cppPath, CCFLAGS = ccFlags)
#Program("awesome", ["main.cpp"] + libmotor + src_states, LIBS = libs, LIBPATH = ".", CPPPATH = cppPath, CCFLAGS = ccFlags, CXX = "ccache " + CC)
Program("hadouken", ["main.cpp"] + libmotor + src_states, LIBS = libs, CPPPATH = cppPath, CCFLAGS = ccFlags, CXX = CC)
